/**
 * Generates the COMUTA design tokens.
 *
 *   design/design-tokens.json  ->  src/generated/colors.ts
 *                              ->  src/generated/typography.ts
 *                              ->  src/generated/tailwind-theme.css
 *
 * `design/design-tokens.json` at the repo root is the canonical contract — a
 * verbatim capture of Figma tGWQGJbGogndVTvpVjzxYa nodes 22:52 (colour) and
 * 29:422 (type). It is NOT owned by this package; it is the design source of
 * truth for every surface. Re-pull it with the Figma MCP when the brand moves,
 * then run `npm run tokens`.
 *
 * Naming here matches the convention already established in the PWA's
 * index.css — primary / accent / tertiary / ntl / nv / danger — so the emitted
 * CSS is a drop-in for the block that was previously hand-maintained there.
 *
 * Never hand-edit anything under src/generated.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(pkgRoot, '../..');
const SOURCE = resolve(repoRoot, 'design/design-tokens.json');

const tokens = JSON.parse(readFileSync(SOURCE, 'utf8'));
const outDir = resolve(pkgRoot, 'src/generated');
mkdirSync(outDir, { recursive: true });

/** Figma ramp name -> the name screens and CSS use. */
const RAMP_ALIAS = {
  primary: 'primary',
  secondary: 'accent',
  tertiary: 'tertiary',
  neutral: 'ntl',
  neutralVariant: 'nv',
  error: 'danger',
};

/** Type role -> CSS custom-property suffix. */
const ROLE_ALIAS = {
  displayLarge: 'display-lg',
  displayMedium: 'display-md',
  displaySmall: 'display-sm',
  headlineLarge: 'headline-lg',
  headlineMedium: 'headline-md',
  headlineSmall: 'headline-sm',
  titleLarge: 'title-lg',
  titleMedium: 'title-md',
  titleSmall: 'title-sm',
  bodyLarge: 'body-lg',
  bodyMedium: 'body-md',
  bodySmall: 'body-sm',
  labelLarge: 'label-lg',
  labelMedium: 'label-md',
  labelSmall: 'label-sm',
};

const src = tokens.$source ?? {};
const BANNER =
  `// AUTO-GENERATED by packages/tokens/scripts/generate.mjs — do not edit.\n` +
  `// Source: design/design-tokens.json (Figma ${src.figmaFileKey}, colour ${src.colorNode}, type ${src.typographyNode})\n`;

/** Tone stops, numerically sorted. `base` is a standalone swatch, not a stop. */
const stops = (ramp) =>
  Object.keys(ramp)
    .filter((k) => k !== 'base' && !k.startsWith('$'))
    .sort((a, b) => Number(a) - Number(b));

/* ── colors.ts ─────────────────────────────────────────────── */
{
  let ts = BANNER + '\n/** Figma tonal ramps. Tone 0 is black and 100 is white in every ramp. */\n';
  ts += 'export const palette = {\n';
  for (const [figmaName, alias] of Object.entries(RAMP_ALIAS)) {
    const ramp = tokens.color[figmaName];
    if (!ramp) throw new Error(`design-tokens.json is missing the "${figmaName}" ramp`);
    ts += `  /** Figma \`${figmaName}\` */\n  ${alias}: {\n`;
    for (const stop of stops(ramp)) ts += `    ${stop}: '${ramp[stop]}',\n`;
    if (ramp.base) {
      ts += `    /** Standalone key swatch — NOT a ramp member. */\n    base: '${ramp.base}',\n`;
    }
    ts += '  },\n';
  }
  ts += '} as const;\n\n';

  if (tokens.semantic) {
    ts += '/**\n * The only colour layer screens are allowed to import.\n';
    ts += ' * Screens never reference a raw tone.\n */\n';
    ts += 'export const semantic = {\n';
    for (const [k, v] of Object.entries(tokens.semantic)) {
      if (k.startsWith('$')) continue;
      ts += `  ${k}: '${v}',\n`;
    }
    ts += '} as const;\n\n';
  }

  ts += 'export type PaletteRamp = keyof typeof palette;\n';
  ts += 'export type Tone = Exclude<keyof typeof palette.primary, "base">;\n';
  ts += 'export type SemanticRole = keyof typeof semantic;\n';
  writeFileSync(resolve(outDir, 'colors.ts'), ts);
}

/* ── typography.ts ─────────────────────────────────────────── */
{
  const t = tokens.typography;
  let ts = BANNER + `\n/** Figma specifies ${t.fontFamily.sans.figma}; ${t.fontFamily.sans.substitute} is the licensed substitute. */\n`;
  ts += `export const figmaFontFamily = '${t.fontFamily.sans.figma}' as const;\n`;
  ts += `export const substituteFontFamily = '${t.fontFamily.sans.substitute}' as const;\n`;
  ts += `export const monoFontFamily = '${t.fontFamily.mono}' as const;\n\n`;
  ts += `export const lineHeightRatio = ${t.lineHeightRatio};\n`;
  ts += `export const letterSpacing = ${t.letterSpacing};\n\n`;
  ts += 'export const typeScale = {\n';
  for (const [role, r] of Object.entries(t.scale)) {
    ts += `  ${role}: { fontSize: ${r.size}, lineHeight: ${r.lineHeight}, fontWeight: '${r.weight}' },\n`;
  }
  ts += '} as const;\n\nexport type TypeRole = keyof typeof typeScale;\n';
  writeFileSync(resolve(outDir, 'typography.ts'), ts);
}

/* ── tailwind-theme.css ────────────────────────────────────── */
{
  let css =
    `/*\n * AUTO-GENERATED by packages/tokens/scripts/generate.mjs — do not edit.\n` +
    ` * Source: design/design-tokens.json (Figma ${src.figmaFileKey}).\n` +
    ` * The canonical brand ramps. Figma is law: NEW work uses these.\n */\n\n@theme {\n`;
  for (const [figmaName, alias] of Object.entries(RAMP_ALIAS)) {
    const ramp = tokens.color[figmaName];
    for (const stop of stops(ramp)) css += `  --color-${alias}-${stop}: ${ramp[stop]};\n`;
    if (ramp.base) {
      css += `  /* standalone key swatch - NOT a ramp member */\n  --color-${alias}-base: ${ramp.base};\n`;
    }
    css += '\n';
  }
  const t = tokens.typography;
  css += `  /* M3 type scale, ${t.fontFamily.sans.figma} -> ${t.fontFamily.sans.substitute}. Flat ${t.lineHeightRatio} line-height, ${t.letterSpacing} tracking. */\n`;
  for (const [role, suffix] of Object.entries(ROLE_ALIAS)) {
    css += `  --text-${suffix}: ${t.scale[role].size}px;\n`;
  }
  css += '}\n';
  writeFileSync(resolve(outDir, 'tailwind-theme.css'), css);
}

console.log(
  `tokens: ${Object.keys(RAMP_ALIAS).length} ramps + ${Object.keys(tokens.semantic ?? {}).filter((k) => !k.startsWith('$')).length} semantic roles + ` +
    `${Object.keys(tokens.typography.scale).length} type roles\n` +
    `        design/design-tokens.json -> packages/tokens/src/generated/`
);
