import { useState } from 'react';
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, BadgeCheck,
  Banknote, BarChart3, Bell, CarFront, Check, CheckCircle2, ChevronDown, ChevronRight,
  CircleDollarSign, Clock3, Command, CreditCard, FileCheck2, Gauge, Headphones, LayoutDashboard,
  MapPin, Menu, MessageSquare, MoreHorizontal, Route, Search, Settings, ShieldAlert, ShieldCheck,
  Siren, SlidersHorizontal, Star, UserCheck, Users, WalletCards, X, Zap,
} from 'lucide-react';
import Brand from './components/Brand';
import { Avatar, Toast } from './components/UI';

type Props = { path: string; onNavigate: (path: string) => void; onExit: () => void; onApp: () => void };

type OpsNavItem = { slug: string; label: string; icon: typeof LayoutDashboard; count?: string; danger?: boolean };

const nav: { group: string; items: OpsNavItem[] }[] = [
  { group: 'OVERVIEW', items: [{slug:'control-centre',label:'Control centre',icon:LayoutDashboard},{slug:'live-trips',label:'Live trips',icon:Route,count:'38'},{slug:'analytics',label:'Analytics',icon:BarChart3},{slug:'reports',label:'Reports',icon:Activity}]},
  { group: 'MARKETPLACE', items: [{slug:'users',label:'Users',icon:Users},{slug:'drivers',label:'Drivers',icon:CarFront},{slug:'vehicles',label:'Vehicles',icon:CarFront},{slug:'trips',label:'Trips',icon:Route},{slug:'bookings',label:'Bookings',icon:CheckCircle2},{slug:'communities',label:'Communities',icon:UserCheck},{slug:'pricing',label:'Pricing',icon:CircleDollarSign},{slug:'promotions',label:'Promotions',icon:Zap}]},
  { group: 'OPERATIONS', items: [{slug:'verification',label:'Verification',icon:FileCheck2,count:'12'},{slug:'safety',label:'Safety',icon:ShieldAlert,count:'2',danger:true},{slug:'disputes',label:'Disputes',icon:MessageSquare,count:'5'},{slug:'settings',label:'Settings',icon:Settings},{slug:'audit-logs',label:'Audit logs',icon:Command}]},
  { group: 'FINANCE', items: [{slug:'payments',label:'Payments',icon:CreditCard},{slug:'refunds',label:'Refunds',icon:ArrowLeft},{slug:'payouts',label:'Payouts',icon:WalletCards}]},
];

export default function OpsDashboard({ path, onNavigate, onExit, onApp }: Props) {
  const [menu,setMenu]=useState(false);
  const [toast,setToast]=useState('');
  const [incidentOpen,setIncidentOpen]=useState(true);
  const [period,setPeriod]=useState('Today');
  const requestedSlug=path.split('/').filter(Boolean)[1] ?? 'control-centre';
  const currentItem=nav.flatMap(group=>group.items).find(item=>item.slug===requestedSlug) ?? nav[0].items[0];
  const currentSlug=currentItem.slug;
  const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2400)};
  const openModule=(slug:string)=>{onNavigate(`/ops/${slug}`);setMenu(false)};
  return <div className="ops-app">
    <aside className={`ops-sidebar ${menu?'open':''}`}>
      <div className="ops-brand"><button onClick={onExit}><Brand inverse/></button><span>OPS</span><button className="ops-close" onClick={()=>setMenu(false)}><X/></button></div>
      <nav>{nav.map(g=><div className="ops-nav-group" key={g.group}><span>{g.group}</span>{g.items.map(({slug,label,icon:Icon,count,danger})=><button key={slug} className={`${currentSlug===slug?'active':''} ${danger?'danger':''}`} onClick={()=>openModule(slug)}><Icon size={17}/><em>{label}</em>{count&&<i>{count}</i>}</button>)}</div>)}</nav>
      <div className="ops-system"><div><span/><strong>All systems operational</strong></div><small>Last checked 10:42:08</small></div>
      <button className="ops-user"><Avatar initials="KA" color="#425c91" size={37}/><span><strong>Kemi A.</strong><small>Operations lead</small></span><MoreHorizontal/></button>
    </aside>
    {menu&&<div className="side-scrim" onClick={()=>setMenu(false)}/>}
    <section className="ops-workspace">
      <header className="ops-topbar"><div><button className="ops-menu" onClick={()=>setMenu(true)}><Menu/></button><span>Operations</span><ChevronRight/><strong>{currentItem.label}</strong></div><div><button className="ops-search"><Search/><span>Search users, trips, payments...</span><kbd>⌘ K</kbd></button><button className="ops-icon"><Bell/><i>3</i></button><button className="ops-icon" onClick={()=>openModule('settings')}><Settings/></button><button className="view-product" onClick={onApp}>View product <ArrowRight/></button></div></header>
      <main className="ops-page">
        {currentSlug==='control-centre'?<>
        <div className="ops-page-head"><div><span>MONDAY · 17 AUGUST 2026 · 10:42 WAT</span><h1>Marketplace control centre</h1><p>Live health across PadiGo's Lagos corridors.</p></div><div className="ops-head-actions"><button className="period-button" onClick={()=>setPeriod(period==='Today'?'This week':'Today')}><Clock3/>{period}<ChevronDown/></button><button className="ops-primary" onClick={()=>notify('Daily report exported')}><BarChart3/>Export report</button></div></div>
        {incidentOpen&&<div className="incident-banner"><span className="incident-icon"><Siren/></span><div><span>ACTIVE SAFETY REVIEW</span><strong>Route deviation detected · Trip #PG4902</strong><p>Driver deviated 2.4 km from expected corridor near Third Mainland Bridge. Rider responded “I’m okay.”</p></div><div><small>OPEN FOR</small><strong>03:18</strong></div><button onClick={()=>notify('Safety case opened')}>Open incident <ArrowRight/></button><button className="dismiss-incident" onClick={()=>setIncidentOpen(false)}><X/></button></div>}
        <div className="ops-stats">
          <Metric icon={<Route/>} label="ACTIVE TRIPS" value="38" sub="106 people moving" trend="+12%" good />
          <Metric icon={<Zap/>} label="COMPLETED TODAY" value="284" sub="74.2% seat fill" trend="+8.4%" good />
          <Metric icon={<Gauge/>} label="MATCH RATE" value="78.6%" sub="Search to match" trend="+2.1%" good />
          <Metric icon={<CircleDollarSign/>} label="TODAY'S GBV" value="₦684k" sub="₦68.4k revenue" trend="+14%" good />
          <Metric icon={<AlertTriangle/>} label="NEEDS ATTENTION" value="19" sub="12 checks · 5 disputes" trend="2 urgent" warning />
        </div>
        <div className="ops-main-grid">
          <section className="ops-panel live-panel"><PanelHead eyebrow="LIVE MARKETPLACE" title="Trips in progress" sub="38 active · Updated just now" action={<><span className="live-status"><i/>Live</span><button onClick={()=>notify('Live trips opened')}>View all <ArrowRight/></button></>}/><div className="ops-map"><OpsMap/><div className="map-cluster mc1">8</div><div className="map-cluster mc2">14</div><div className="map-cluster mc3">5</div><span className="trip-dot td1"/><span className="trip-dot td2"/><span className="trip-dot td3 warning"/><div className="ops-map-card"><div><span><i className="normal"/>IN PROGRESS</span><small>#PG8321</small></div><strong>Ajah <ArrowRight/> Victoria Island</strong><p><Avatar initials="AB" color="#c87451" size={27}/> Ade B. · 3 riders</p><span>ETA · 18 MIN</span></div><div className="map-legend"><span><i/>Normal</span><span><i className="delayed"/>Delayed</span><span><i className="review"/>Review</span></div></div></section>
          <section className="ops-panel corridor-panel"><PanelHead eyebrow="MARKET LIQUIDITY" title="Corridor health" sub="Morning window · 6:00 AM to 10:00 AM" action={<button><SlidersHorizontal/></button>}/><div className="corridor-head"><span>CORRIDOR</span><span>DEMAND / SEATS</span><span>FILL</span><span>STATUS</span></div><Corridor name="Ajah → VI" demand={184} seats={126} fill={82} status="Supply gap" warn/><Corridor name="Ikeja → VI" demand={96} seats={104} fill={71} status="Balanced"/><Corridor name="Yaba → Lekki" demand={73} seats={68} fill={79} status="Healthy"/><Corridor name="Berger → VI" demand={88} seats={42} fill={91} status="Critical gap" danger/><Corridor name="Ikorodu → Ikeja" demand={51} seats={60} fill={64} status="Building"/><button className="panel-bottom-button">Open liquidity analytics <ArrowRight/></button></section>
        </div>
        <div className="ops-second-grid">
          <section className="ops-panel performance-panel"><PanelHead eyebrow="COMPLETION FUNNEL" title="Today's marketplace" sub="1,842 ride searches" action={<select><option>Today</option><option>This week</option></select>}/><div className="funnel"><div><span>SEARCHES</span><strong>1,842</strong><i><em style={{width:'100%'}}/></i><small>100%</small></div><ArrowDownRight/><div><span>MATCHED</span><strong>1,448</strong><i><em style={{width:'78.6%'}}/></i><small>78.6%</small></div><ArrowDownRight/><div><span>BOOKED</span><strong>522</strong><i><em style={{width:'54%'}}/></i><small>36.0%</small></div><ArrowDownRight/><div><span>COMPLETED</span><strong>284</strong><i><em style={{width:'34%'}}/></i><small>54.4%</small></div></div><div className="funnel-note"><TrendingBadge/> <span><strong>Booking conversion is up 4.2%</strong> after reducing Ajah pickup radius to 1.2 km.</span></div></section>
          <section className="ops-panel queue-panel"><PanelHead eyebrow="ACTION QUEUE" title="Needs your team" sub="19 open items" action={<button>View queue <ArrowRight/></button>}/><QueueRow icon={<ShieldAlert/>} color="red" title="Safety reviews" detail="1 urgent · 1 awaiting follow up" count="2"/><QueueRow icon={<FileCheck2/>} color="amber" title="Driver verifications" detail="Oldest waiting 46 minutes" count="12"/><QueueRow icon={<MessageSquare/>} color="purple" title="Open disputes" detail="₦18,500 total at risk" count="5"/><QueueRow icon={<Banknote/>} color="blue" title="Payout exceptions" detail="All cleared" count="0" muted/></section>
        </div>
        <section className="ops-panel verification-table"><PanelHead eyebrow="VERIFICATION OPS" title="Recent driver applications" sub="12 waiting for review" action={<div className="table-actions"><button><SlidersHorizontal/>Filter</button><button onClick={()=>openModule('verification')}>Open full queue <ArrowRight/></button></div>}/><div className="ops-table"><div className="ops-tr th"><span>APPLICANT</span><span>VEHICLE</span><span>DOCUMENTS</span><span>RISK</span><span>WAITING</span><span>ACTION</span></div><Applicant initials="FE" color="#6b58a3" name="Femi Eze" phone="0803 ••• 8842" vehicle="Toyota Camry · LSR 204 FT" docs="5 of 6 checked" risk="Low" time="18 min" notify={notify}/><Applicant initials="BN" color="#bc7352" name="Bola Nwankwo" phone="0812 ••• 1409" vehicle="Honda Accord · KJA 918 GE" docs="4 of 6 checked" risk="Review" time="31 min" notify={notify}/><Applicant initials="ML" color="#34796a" name="Musa Lawal" phone="0706 ••• 2391" vehicle="Kia Rio · GGE 774 BX" docs="6 of 6 checked" risk="Low" time="46 min" notify={notify}/></div></section>
        </>:<OpsModulePage slug={currentSlug} notify={notify}/>}
      </main>
    </section>
    <Toast visible={!!toast} message={toast}/>
  </div>
}

type ModuleRow = { reference: string; primary: string; secondary: string; status: string; updated: string };
type ModuleData = { eyebrow: string; title: string; description: string; metrics: [string,string][]; rows: ModuleRow[] };

const moduleData: Record<string, ModuleData> = {
  'live-trips': {eyebrow:'LIVE OPERATIONS',title:'Live trips',description:'Monitor active journeys, timing and route exceptions across every open corridor.',metrics:[['38','ACTIVE NOW'],['106','PEOPLE MOVING'],['4','DELAYED'],['2','UNDER REVIEW']],rows:[{reference:'PG8321',primary:'Ajah to Victoria Island',secondary:'Ade B. · 3 riders',status:'In progress',updated:'18 min ETA'},{reference:'PG4902',primary:'Yaba to Lekki',secondary:'Route deviation review',status:'Review',updated:'Opened 3 min ago'},{reference:'PG7741',primary:'Ikeja to Victoria Island',secondary:'Ifeoma N. · 2 riders',status:'On route',updated:'27 min ETA'}]},
  analytics: {eyebrow:'MARKET INTELLIGENCE',title:'Analytics',description:'Compare demand, matching, booking and completion performance by corridor and time window.',metrics:[['78.6%','MATCH RATE'],['36.0%','BOOKING RATE'],['54.4%','COMPLETION RATE'],['74.2%','SEAT FILL']],rows:[{reference:'Ajah to VI',primary:'Morning commute',secondary:'184 searches · 126 seats',status:'Supply gap',updated:'+12% demand'},{reference:'Ikeja to VI',primary:'Morning commute',secondary:'96 searches · 104 seats',status:'Balanced',updated:'+4% bookings'},{reference:'Yaba to Lekki',primary:'Evening commute',secondary:'73 searches · 68 seats',status:'Healthy',updated:'+8% fill'}]},
  reports: {eyebrow:'REPORTING',title:'Reports',description:'Generate scheduled marketplace, safety, finance and verification reports for the operations team.',metrics:[['12','SCHEDULED'],['4','READY'],['2','PROCESSING'],['31','THIS MONTH']],rows:[{reference:'RPT0826A',primary:'Daily marketplace summary',secondary:'Trips, bookings and corridor health',status:'Ready',updated:'Today · 10:30'},{reference:'RPT0826B',primary:'Weekly safety review',secondary:'Cases, response and resolution',status:'Scheduled',updated:'Friday · 17:00'},{reference:'RPT0826C',primary:'Settlement reconciliation',secondary:'Payments, refunds and payouts',status:'Processing',updated:'Started 8 min ago'}]},
  users: {eyebrow:'MEMBER OPERATIONS',title:'Users',description:'Review rider accounts, identity status, trip history, communities and account restrictions.',metrics:[['12,480','TOTAL USERS'],['8,942','VERIFIED'],['1,208','ACTIVE WEEKLY'],['23','RESTRICTED']],rows:[{reference:'USR2048',primary:'Tobi Nwankwo',secondary:'Rider · PadiGo at Sterling',status:'Verified',updated:'Active today'},{reference:'USR3091',primary:'Amaka Eze',secondary:'Rider · Lekki Gardens',status:'Verified',updated:'Active yesterday'},{reference:'USR1184',primary:'Kunle Adeyemi',secondary:'Rider · No community',status:'Review',updated:'Flagged 24 min ago'}]},
  drivers: {eyebrow:'DRIVER OPERATIONS',title:'Drivers',description:'Manage driver identity, performance, availability, earnings and marketplace standing.',metrics:[['1,284','APPROVED'],['842','ACTIVE WEEKLY'],['4.86','AVG RATING'],['12','PENDING REVIEW']],rows:[{reference:'DRV0184',primary:'Ade Bamidele',secondary:'Toyota Corolla · 184 trips',status:'Approved',updated:'Online now'},{reference:'DRV0296',primary:'Ifeoma Nwosu',secondary:'Honda Accord · 96 trips',status:'Approved',updated:'Online 12 min ago'},{reference:'DRV0412',primary:'Femi Eze',secondary:'Toyota Camry · Application',status:'Review',updated:'Waiting 18 min'}]},
  vehicles: {eyebrow:'FLEET TRUST',title:'Vehicles',description:'Inspect approved vehicles, documents, seat capacity and renewal requirements.',metrics:[['1,396','REGISTERED'],['1,301','APPROVED'],['71','RENEWALS DUE'],['24','UNDER REVIEW']],rows:[{reference:'APP 412 GH',primary:'Toyota Corolla · Silver',secondary:'Ade Bamidele · 4 seats',status:'Approved',updated:'Insurance due 93 days'},{reference:'KJA 208 FT',primary:'Honda Accord · Black',secondary:'Ifeoma Nwosu · 4 seats',status:'Approved',updated:'Updated 3 days ago'},{reference:'LSR 204 FT',primary:'Toyota Camry · Grey',secondary:'Femi Eze · 4 seats',status:'Review',updated:'Document pending'}]},
  trips: {eyebrow:'TRIP OPERATIONS',title:'Trips',description:'Search scheduled, active, completed and cancelled trip records with full state timelines.',metrics:[['38','ACTIVE'],['284','COMPLETED TODAY'],['16','CANCELLED'],['4','DELAYED']],rows:[{reference:'PG8321',primary:'Ajah to Victoria Island',secondary:'3 riders · ₦4,500 value',status:'In progress',updated:'Started 34 min ago'},{reference:'PG7741',primary:'Ikeja to Victoria Island',secondary:'2 riders · ₦3,200 value',status:'Scheduled',updated:'Starts 12:30'},{reference:'PG6804',primary:'Yaba to Lekki',secondary:'3 riders · ₦3,900 value',status:'Completed',updated:'Ended 09:18'}]},
  bookings: {eyebrow:'SEAT OPERATIONS',title:'Bookings',description:'Follow each seat request from driver acceptance and payment through completion or cancellation.',metrics:[['522','BOOKED TODAY'],['47','PAYMENT PENDING'],['18','CANCELLED'],['6','DISPUTED']],rows:[{reference:'BKG9012',primary:'Tobi N. · Trip PG8321',secondary:'1 seat · ₦1,500',status:'Paid',updated:'Confirmed 06:42'},{reference:'BKG9018',primary:'Amaka E. · Trip PG7741',secondary:'1 seat · ₦1,600',status:'Accepted',updated:'Payment due 8 min'},{reference:'BKG8977',primary:'Kunle A. · Trip PG6804',secondary:'1 seat · ₦1,300',status:'Cancelled',updated:'Refund started'}]},
  communities: {eyebrow:'COMMUNITY OPERATIONS',title:'Communities',description:'Manage trusted groups, membership checks, route activity and community administrators.',metrics:[['184','ACTIVE GROUPS'],['18,420','MEMBERS'],['642','ACTIVE ROUTES'],['14','PENDING']],rows:[{reference:'COM0012',primary:'PadiGo at Sterling',secondary:'Workplace · 428 members',status:'Verified',updated:'64 rides this week'},{reference:'COM0031',primary:'Lekki Gardens',secondary:'Estate · 216 members',status:'Verified',updated:'28 rides this week'},{reference:'COM0088',primary:'Mainland Tech Circle',secondary:'Association · 184 members',status:'Review',updated:'Admin check pending'}]},
  pricing: {eyebrow:'MARKET PRICING',title:'Pricing',description:'Maintain fair contribution guidance by corridor while drivers retain control within approved limits.',metrics:[['₦1,420','AVG SEAT'],['24','CORRIDORS'],['6','PRICE RULES'],['2','REVIEWS DUE']],rows:[{reference:'PRC001',primary:'Ajah to Victoria Island',secondary:'28.6 km · Morning window',status:'₦1,300 to ₦1,650',updated:'Updated 2 days ago'},{reference:'PRC002',primary:'Ikeja to Victoria Island',secondary:'21.4 km · Morning window',status:'₦1,100 to ₦1,450',updated:'Updated 5 days ago'},{reference:'PRC003',primary:'Yaba to Lekki',secondary:'14.8 km · Evening window',status:'Review',updated:'Demand changed 14%'}]},
  promotions: {eyebrow:'GROWTH OPERATIONS',title:'Promotions',description:'Create targeted corridor incentives and track redemptions without changing transparent seat pricing.',metrics:[['8','ACTIVE'],['2,418','REDEMPTIONS'],['₦1.8m','CREDIT USED'],['31%','REPEAT RATE']],rows:[{reference:'WELCOME500',primary:'First verified booking',secondary:'Selected Lagos corridors',status:'Active',updated:'842 redemptions'},{reference:'AJAHWEEK',primary:'Ajah recurring commute',secondary:'Three weekday bookings',status:'Active',updated:'614 redemptions'},{reference:'DRIVERSEATS',primary:'New driver route launch',secondary:'Complete first five trips',status:'Scheduled',updated:'Starts Monday'}]},
  verification: {eyebrow:'TRUST OPERATIONS',title:'Verification',description:'Review identity, liveness, driver licence, vehicle and community verification queues.',metrics:[['12','DRIVERS WAITING'],['34','IDENTITY CHECKS'],['8','VEHICLE CHECKS'],['9 min','AVG REVIEW']],rows:[{reference:'VER2048',primary:'Femi Eze',secondary:'Driver · 5 of 6 checks complete',status:'Low risk',updated:'Waiting 18 min'},{reference:'VER2061',primary:'Bola Nwankwo',secondary:'Driver · 4 of 6 checks complete',status:'Review',updated:'Waiting 31 min'},{reference:'VER2074',primary:'Musa Lawal',secondary:'Vehicle renewal · 6 checks',status:'Low risk',updated:'Waiting 46 min'}]},
  safety: {eyebrow:'SAFETY OPERATIONS',title:'Safety',description:'Triage SOS events, route deviations, reports and account actions with complete trip context.',metrics:[['2','ACTIVE CASES'],['1','URGENT'],['6 min','AVG RESPONSE'],['94%','CLOSED IN TARGET']],rows:[{reference:'SAFE4902',primary:'Route deviation · Trip PG4902',secondary:'Rider responded and tracking continues',status:'Active review',updated:'Opened 3 min ago'},{reference:'SAFE4877',primary:'Rider conduct report',secondary:'Trip PG6804 · Driver submitted',status:'Evidence review',updated:'Opened 42 min ago'},{reference:'SAFE4821',primary:'Emergency contact alert',secondary:'Trip PG6620 · Resolved',status:'Closed',updated:'Closed yesterday'}]},
  disputes: {eyebrow:'RESOLUTION OPERATIONS',title:'Disputes',description:'Review trip evidence, payment context and member communication to resolve marketplace disputes.',metrics:[['5','OPEN'],['₦18,500','VALUE AT RISK'],['1.8 days','AVG RESOLUTION'],['92%','IN TARGET']],rows:[{reference:'DSP1042',primary:'Trip did not start',secondary:'Booking BKG8872 · ₦1,500',status:'Driver response due',updated:'Opened 2 hours ago'},{reference:'DSP1038',primary:'Unexpected cancellation',secondary:'Booking BKG8814 · ₦1,350',status:'Evidence review',updated:'Opened yesterday'},{reference:'DSP1021',primary:'Route completion question',secondary:'Booking BKG8742 · ₦1,600',status:'Resolved',updated:'Closed yesterday'}]},
  settings: {eyebrow:'PLATFORM CONTROLS',title:'Settings',description:'Manage marketplace policies, access roles, notification templates and operational thresholds.',metrics:[['24','ACTIVE POLICIES'],['8','STAFF ROLES'],['16','TEMPLATES'],['2','CHANGES PENDING']],rows:[{reference:'SET001',primary:'Marketplace state rules',secondary:'Booking and trip transitions',status:'Active',updated:'Changed 8 days ago'},{reference:'SET002',primary:'Safety response thresholds',secondary:'Deviation and escalation rules',status:'Active',updated:'Changed 3 days ago'},{reference:'SET003',primary:'Operations permissions',secondary:'Role access review',status:'Review',updated:'Approval pending'}]},
  'audit-logs': {eyebrow:'ACCOUNTABILITY',title:'Audit logs',description:'Review sensitive staff actions across verification, safety, finance and account administration.',metrics:[['18,402','EVENTS THIS MONTH'],['842','TODAY'],['0','FAILED EXPORTS'],['365 days','RETENTION']],rows:[{reference:'AUD88214',primary:'Verification approved',secondary:'Kemi A. · Driver DRV0184',status:'Recorded',updated:'10:38 WAT'},{reference:'AUD88209',primary:'Safety case opened',secondary:'Tunde M. · Case SAFE4902',status:'Recorded',updated:'10:34 WAT'},{reference:'AUD88194',primary:'Refund authorised',secondary:'Ada N. · Refund RFD2208',status:'Recorded',updated:'10:21 WAT'}]},
  payments: {eyebrow:'PAYMENT OPERATIONS',title:'Payments',description:'Monitor collections, authorisations, failures and settlement states across every booking.',metrics:[['₦684k','COLLECTED TODAY'],['522','SUCCESSFUL'],['17','PENDING'],['8','FAILED']],rows:[{reference:'PAY8821',primary:'Booking BKG9012',secondary:'Card · ₦1,500',status:'Paid',updated:'06:42 WAT'},{reference:'PAY8828',primary:'Booking BKG9018',secondary:'Bank transfer · ₦1,600',status:'Pending',updated:'Expires in 8 min'},{reference:'PAY8794',primary:'Booking BKG8970',secondary:'Card · ₦1,350',status:'Failed',updated:'Retry available'}]},
  refunds: {eyebrow:'REFUND OPERATIONS',title:'Refunds',description:'Track requested, approved, processing and completed refunds with booking evidence.',metrics:[['18','OPEN'],['₦42,600','PROCESSING'],['2.4 hrs','AVG APPROVAL'],['96%','COMPLETED IN TARGET']],rows:[{reference:'RFD2208',primary:'Booking BKG8977',secondary:'Cancelled before driver departure',status:'Processing',updated:'Approved 14 min ago'},{reference:'RFD2196',primary:'Booking BKG8942',secondary:'Payment duplicated',status:'Review',updated:'Opened 48 min ago'},{reference:'RFD2181',primary:'Booking BKG8890',secondary:'Driver cancelled trip',status:'Completed',updated:'Sent yesterday'}]},
  payouts: {eyebrow:'PAYOUT OPERATIONS',title:'Payouts',description:'Reconcile driver balances, scheduled transfers and payout exceptions after trip settlement.',metrics:[['₦4.8m','DUE THIS WEEK'],['842','DRIVERS'],['7','EXCEPTIONS'],['99.2%','SUCCESS RATE']],rows:[{reference:'OUT6621',primary:'Ade Bamidele',secondary:'GTBank · ₦46,850',status:'Scheduled',updated:'Friday, 21 August'},{reference:'OUT6634',primary:'Ifeoma Nwosu',secondary:'Access Bank · ₦38,400',status:'Scheduled',updated:'Friday, 21 August'},{reference:'OUT6598',primary:'Musa Lawal',secondary:'GTBank · ₦29,650',status:'Exception',updated:'Account review needed'}]},
};

function OpsModulePage({slug,notify}:{slug:string;notify:(s:string)=>void}){
  const data=moduleData[slug] ?? moduleData.analytics;
  return <div className="ops-module-page">
    <div className="ops-page-head"><div><span>{data.eyebrow}</span><h1>{data.title}</h1><p>{data.description}</p></div><div className="ops-head-actions"><button className="period-button"><SlidersHorizontal/>Filters<ChevronDown/></button><button className="ops-primary" onClick={()=>notify(`${data.title} export started`)}><ArrowDownRight/>Export</button></div></div>
    <div className="module-metrics">{data.metrics.map(([value,label],index)=><article key={label}><span>{label}</span><strong>{value}</strong><small>{index===0?'Primary operational measure':'Updated just now'}</small></article>)}</div>
    <section className="ops-panel module-table-panel">
      <div className="module-toolbar"><div><h2>{data.title} queue</h2><p>Current records requiring visibility or action</p></div><div><button><Search/>Search</button><button><SlidersHorizontal/>Filter</button><button className="module-create" onClick={()=>notify(`New ${data.title.toLowerCase()} action opened`)}>Create action</button></div></div>
      <div className="module-table"><div className="module-row module-head"><span>REFERENCE</span><span>RECORD</span><span>DETAIL</span><span>STATUS</span><span>UPDATED</span><span>ACTION</span></div>{data.rows.map(row=><div className="module-row" key={row.reference}><span><strong>{row.reference}</strong></span><span><strong>{row.primary}</strong></span><span>{row.secondary}</span><span><i/>{row.status}</span><span>{row.updated}</span><span><button onClick={()=>notify(`${row.reference} opened`)}>Open <ArrowRight/></button></span></div>)}</div>
    </section>
    <div className="module-lower-grid"><section className="ops-panel"><PanelHead eyebrow="WORK QUEUE" title="Operations checklist" sub="Suggested actions for this module" action={<button>View policy <ArrowRight/></button>}/><QueueRow icon={<CheckCircle2/>} color="blue" title="Review pending records" detail="Start with the oldest open item" count="1"/><QueueRow icon={<ShieldCheck/>} color="amber" title="Confirm policy compliance" detail="Evidence and access are logged" count="2"/><QueueRow icon={<Activity/>} color="purple" title="Monitor outcome" detail="Marketplace signals update live" count="3"/></section><section className="ops-panel module-note"><ShieldCheck/><span><small>PLATFORM CONTROL</small><h3>Backend authority remains required</h3><p>Permissions, trip states, money movement, seat allocation and safety actions must be validated by the API before any change is applied.</p></span></section></div>
  </div>
}

function Metric({icon,label,value,sub,trend,good,warning}:{icon:React.ReactNode;label:string;value:string;sub:string;trend:string;good?:boolean;warning?:boolean}){return <article className={`ops-metric ${warning?'warning':''}`}><div><span className="metric-icon">{icon}</span><span className="metric-label">{label}</span></div><strong>{value}</strong><p>{sub}<span className={good?'good':warning?'warn':''}>{good?<ArrowUpRight/>:warning?<AlertTriangle/>:null}{trend}</span></p></article>}
function PanelHead({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action:React.ReactNode}){return <div className="ops-panel-head"><div><span>{eyebrow}</span><h2>{title}</h2><p>{sub}</p></div><div>{action}</div></div>}
function Corridor({name,demand,seats,fill,status,warn,danger}:{name:string;demand:number;seats:number;fill:number;status:string;warn?:boolean;danger?:boolean}){return <div className="corridor-row"><strong>{name}</strong><div><span><b>{demand}</b> / {seats}</span><i><em style={{width:`${Math.min(100,seats/demand*100)}%`}}/></i></div><strong>{fill}%</strong><span className={`corridor-status ${danger?'danger':warn?'warn':''}`}><i/>{status}</span></div>}
function QueueRow({icon,color,title,detail,count,muted}:{icon:React.ReactNode;color:string;title:string;detail:string;count:string;muted?:boolean}){return <button className={`queue-row ${muted?'muted':''}`}><span className={color}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><b>{count}</b><ChevronRight/></button>}
function Applicant({initials,color,name,phone,vehicle,docs,risk,time,notify}:{initials:string;color:string;name:string;phone:string;vehicle:string;docs:string;risk:string;time:string;notify:(s:string)=>void}){return <div className="ops-tr"><span className="applicant"><Avatar initials={initials} color={color} size={35}/><em><strong>{name}</strong><small>{phone}</small></em></span><span><strong>{vehicle.split(' · ')[0]}</strong><small>{vehicle.split(' · ')[1]}</small></span><span className="doc-progress"><strong>{docs}</strong><i><em style={{width:docs.startsWith('6')?'100%':docs.startsWith('5')?'83%':'66%'}}/></i></span><span><i className={`risk-tag ${risk==='Review'?'review':''}`}><b/>{risk}</i></span><span><Clock3/>{time}</span><span><button onClick={()=>notify(`${name}'s application opened`)}>Review <ArrowRight/></button></span></div>}
function TrendingBadge(){return <span className="trending-badge"><ArrowUpRight/></span>}
function OpsMap(){return <><span className="om-water"/><span className="om-road r1"/><span className="om-road r2"/><span className="om-road r3"/><span className="om-road r4"/><span className="om-block b1"/><span className="om-block b2"/><span className="om-block b3"/><span className="om-label l1">AJAH</span><span className="om-label l2">VICTORIA ISLAND</span><span className="om-label l3">IKEJA</span><span className="om-label l4">YABA</span><svg viewBox="0 0 700 430"><path d="M620 370 C520 318 470 363 388 292 S270 205 172 217 S102 102 60 75"/><path d="M94 342 C181 275 235 315 312 245 S430 166 552 124"/></svg></>}
