import type { Community, LedgerEntry, Member, PlatformState, RideOffer, Vehicle } from './types';

export const DEMO_PHONE = '08031112841';
export const DEMO_OTP = '4827';
export const DEMO_USER_ID = 'usr_olabisi';
export const STORAGE_KEY = 'comuta.v1';

export const COMMUNITIES: Community[] = [
  { id: 'com_sterling', name: 'Comuta at Sterling', type: 'Workplace', members: '428', routes: 12, color: '#d9efe4', initials: 'ST' },
  { id: 'com_lekki', name: 'Lekki Gardens', type: 'Estate', members: '216', routes: 8, color: '#eef8fa', initials: 'LG' },
  { id: 'com_vi_tech', name: 'VI Tech Circle', type: 'Professional', members: '1.2k', routes: 26, color: '#e8edf1', initials: 'VT' },
  { id: 'com_unilag', name: 'UNILAG Community', type: 'University', members: '863', routes: 19, color: '#e1efff', initials: 'UL' },
  { id: 'com_chevron', name: 'Chevron Estate', type: 'Estate', members: '190', routes: 7, color: '#f3f9dd', initials: 'CE' },
];

const members: Member[] = [
  {
    id: DEMO_USER_ID,
    firstName: 'Olabisi',
    lastName: 'Ojo',
    phone: DEMO_PHONE,
    email: 'olabisi@comuta.ng',
    initials: 'OO',
    avatarColor: '#155942',
    rating: 4.9,
    trips: 28,
    verified: true,
    communityIds: ['com_sterling'],
    emergencyContacts: [{ name: 'Funmi Ojo', phone: '0805 441 2290', relation: 'Mother' }],
    licenceNumber: 'LAG-20491832',
    bankName: 'Guaranty Trust Bank',
    bankLast4: '0294',
    cardLast4: '2048',
  },
  {
    id: 'usr_ade',
    firstName: 'Ade',
    lastName: 'Bamidele',
    phone: '0802 441 1182',
    initials: 'AB',
    avatarColor: '#2e7d8a',
    photo: '/images/people/ade.jpg',
    rating: 4.9,
    trips: 184,
    verified: true,
    communityIds: ['com_sterling'],
    emergencyContacts: [],
    licenceNumber: 'LAG-11820344',
    bankName: 'Access Bank',
    bankLast4: '4412',
  },
  {
    id: 'usr_ifeoma',
    firstName: 'Ifeoma',
    lastName: 'Nwosu',
    phone: '0813 220 9041',
    initials: 'IN',
    avatarColor: '#769e12',
    photo: '/images/people/ifeoma.jpg',
    rating: 4.8,
    trips: 96,
    verified: true,
    communityIds: ['com_lekki'],
    emergencyContacts: [],
    licenceNumber: 'LAG-90331120',
  },
  {
    id: 'usr_musa',
    firstName: 'Musa',
    lastName: 'Lawal',
    phone: '0706 239 1104',
    initials: 'ML',
    avatarColor: '#1d6e53',
    photo: '/images/people/musa.jpg',
    rating: 4.9,
    trips: 231,
    verified: true,
    communityIds: ['com_vi_tech'],
    emergencyContacts: [],
  },
  {
    id: 'usr_dami',
    firstName: 'Damilola',
    lastName: 'James',
    phone: '0809 332 4410',
    initials: 'DJ',
    avatarColor: '#23626d',
    photo: '/images/people/seyi.jpg',
    rating: 4.7,
    trips: 54,
    verified: true,
    communityIds: ['com_chevron'],
    emergencyContacts: [],
  },
  {
    id: 'usr_tobi',
    firstName: 'Tobi',
    lastName: 'Nwankwo',
    phone: '0812 667 3901',
    initials: 'TN',
    avatarColor: '#5c7186',
    photo: '/images/people/chidi.jpg',
    rating: 4.8,
    trips: 17,
    verified: true,
    communityIds: ['com_sterling'],
    emergencyContacts: [],
  },
  {
    id: 'usr_amaka',
    firstName: 'Amaka',
    lastName: 'Eze',
    phone: '0805 118 2293',
    initials: 'AE',
    avatarColor: '#2a8a68',
    photo: '/images/people/amaka.jpg',
    rating: 4.9,
    trips: 41,
    verified: true,
    communityIds: ['com_lekki'],
    emergencyContacts: [],
  },
  {
    id: 'usr_chidi',
    firstName: 'Chidi',
    lastName: 'Okafor',
    phone: '0803 991 2044',
    initials: 'CO',
    avatarColor: '#0f4431',
    photo: '/images/people/chidi.jpg',
    rating: 4.8,
    trips: 62,
    verified: true,
    communityIds: ['com_unilag'],
    emergencyContacts: [],
  },
  {
    id: 'usr_seyi',
    firstName: 'Seyi',
    lastName: 'Okunola',
    phone: '0816 440 2281',
    initials: 'SO',
    avatarColor: '#4a6584',
    photo: '/images/people/seyi.jpg',
    rating: 4.9,
    trips: 73,
    verified: true,
    communityIds: ['com_unilag'],
    emergencyContacts: [],
  },
  {
    id: 'usr_tolu',
    firstName: 'Tolu',
    lastName: 'Adeyemi',
    phone: '0807 220 1184',
    initials: 'TA',
    avatarColor: '#3d5a80',
    photo: '/images/people/tolu.jpg',
    rating: 4.9,
    trips: 38,
    verified: true,
    communityIds: ['com_lekki'],
    emergencyContacts: [],
  },
];

const vehicles: Vehicle[] = [
  { id: 'veh_ade', driverId: 'usr_ade', make: 'Toyota', model: 'Corolla', color: 'Silver', plate: 'APP 412 GH', seats: 4, year: 2018 },
  { id: 'veh_ifeoma', driverId: 'usr_ifeoma', make: 'Honda', model: 'Accord', color: 'Black', plate: 'KJA 208 FT', seats: 4, year: 2019 },
  { id: 'veh_musa', driverId: 'usr_musa', make: 'Kia', model: 'Rio', color: 'Blue', plate: 'GGE 774 BX', seats: 4, year: 2020 },
  { id: 'veh_dami', driverId: 'usr_dami', make: 'Hyundai', model: 'Elantra', color: 'Grey', plate: 'KSF 331 AQ', seats: 4, year: 2017 },
  { id: 'veh_chidi', driverId: 'usr_chidi', make: 'Toyota', model: 'Camry', color: 'White', plate: 'LND 902 EK', seats: 4, year: 2016 },
  { id: 'veh_seyi', driverId: 'usr_seyi', make: 'Honda', model: 'Civic', color: 'Red', plate: 'APP 118 LK', seats: 4, year: 2021 },
  { id: 'veh_tolu', driverId: 'usr_tolu', make: 'Toyota', model: 'Corolla', color: 'Blue', plate: 'KJA 441 PL', seats: 4, year: 2018 },
  { id: 'veh_olabisi', driverId: DEMO_USER_ID, make: 'Toyota', model: 'Corolla', color: 'White', plate: 'APP 774 KD', seats: 4, year: 2019 },
];

const weekdays = [1, 2, 3, 4, 5];

const rides: RideOffer[] = [
  {
    id: 'CT2841',
    driverId: 'usr_ade',
    vehicleId: 'veh_ade',
    fromId: 'ajah',
    toId: 'vi',
    pickupId: 'novare',
    dropoffId: 'ozumba',
    time: '7:05 AM',
    durationMin: 42,
    distanceKm: 28.6,
    price: 1500,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_sterling',
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT3027',
    driverId: 'usr_ifeoma',
    vehicleId: 'veh_ifeoma',
    fromId: 'ajah',
    toId: 'vi',
    pickupId: 'adesanya',
    dropoffId: 'sterling',
    time: '6:55 AM',
    durationMin: 47,
    distanceKm: 29.1,
    price: 1350,
    seats: 3,
    seatsLeft: 1,
    recurring: true,
    days: weekdays,
    communityId: 'com_lekki',
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT1913',
    driverId: 'usr_musa',
    vehicleId: 'veh_musa',
    fromId: 'sangotedo',
    toId: 'oniru',
    pickupId: 'monastery',
    dropoffId: 'oniru',
    time: '7:15 AM',
    durationMin: 39,
    distanceKm: 24.4,
    price: 1250,
    seats: 3,
    seatsLeft: 3,
    recurring: false,
    days: weekdays,
    communityId: 'com_vi_tech',
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT4388',
    driverId: 'usr_dami',
    vehicleId: 'veh_dami',
    fromId: 'ajah',
    toId: 'vi',
    pickupId: 'chevron',
    dropoffId: 'lawschool',
    time: '7:25 AM',
    durationMin: 44,
    distanceKm: 26.8,
    price: 1100,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_chevron',
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT5510',
    driverId: 'usr_chidi',
    vehicleId: 'veh_chidi',
    fromId: 'ikeja',
    toId: 'vi',
    pickupId: 'ikeja',
    dropoffId: 'ozumba',
    time: '7:10 AM',
    durationMin: 51,
    distanceKm: 22.4,
    price: 1400,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_vi_tech',
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT6621',
    driverId: 'usr_seyi',
    vehicleId: 'veh_seyi',
    fromId: 'yaba',
    toId: 'lekki',
    pickupId: 'unilag',
    dropoffId: 'lekki',
    time: '7:20 AM',
    durationMin: 36,
    distanceKm: 16.2,
    price: 1200,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_unilag',
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT7704',
    driverId: 'usr_tolu',
    vehicleId: 'veh_tolu',
    fromId: 'berger',
    toId: 'vi',
    pickupId: 'berger',
    dropoffId: 'sterling',
    time: '6:40 AM',
    durationMin: 58,
    distanceKm: 31.2,
    price: 1600,
    seats: 3,
    seatsLeft: 1,
    recurring: true,
    days: weekdays,
    status: 'published',
    when: 'tomorrow',
  },
  {
    id: 'CT8824',
    driverId: DEMO_USER_ID,
    vehicleId: 'veh_olabisi',
    fromId: 'vi',
    toId: 'ajah',
    pickupId: 'sterling',
    dropoffId: 'novare',
    time: '5:30 PM',
    durationMin: 48,
    distanceKm: 28.6,
    price: 1500,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_sterling',
    status: 'published',
    when: 'today',
  },
  {
    id: 'CT8901',
    driverId: DEMO_USER_ID,
    vehicleId: 'veh_olabisi',
    fromId: 'vi',
    toId: 'ajah',
    pickupId: 'sterling',
    dropoffId: 'novare',
    time: '5:30 PM',
    durationMin: 48,
    distanceKm: 28.6,
    price: 1500,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_sterling',
    status: 'published',
    when: 'friday',
  },
  {
    id: 'CT9102',
    driverId: 'usr_ifeoma',
    vehicleId: 'veh_ifeoma',
    fromId: 'vi',
    toId: 'ajah',
    pickupId: 'ozumba',
    dropoffId: 'adesanya',
    time: '5:30 PM',
    durationMin: 46,
    distanceKm: 28.2,
    price: 1350,
    seats: 3,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_lekki',
    status: 'published',
    when: 'friday',
  },
];

const now = () => new Date().toISOString();
const minutesAgo = (n: number) => new Date(Date.now() - n * 60000).toISOString();

const ledger: LedgerEntry[] = [
  { id: 'led_1', memberId: DEMO_USER_ID, type: 'settlement', amount: 2850, status: 'completed', reference: 'CT8701', note: 'Ajah → Victoria Island', createdAt: minutesAgo(60 * 24 * 4) },
  { id: 'led_2', memberId: DEMO_USER_ID, type: 'settlement', amount: 4200, status: 'completed', reference: 'CT8710', note: 'Victoria Island → Ajah', createdAt: minutesAgo(60 * 24 * 3) },
  { id: 'led_3', memberId: DEMO_USER_ID, type: 'withdrawal', amount: -32700, status: 'completed', reference: 'OUT6590', note: 'Weekly payout · GTBank ••0294', createdAt: minutesAgo(60 * 24 * 6) },
  { id: 'led_4', memberId: DEMO_USER_ID, type: 'settlement', amount: 2700, status: 'completed', reference: 'CT8722', note: 'Ajah → Victoria Island', createdAt: minutesAgo(60 * 24 * 2) },
  { id: 'led_5', memberId: DEMO_USER_ID, type: 'settlement', amount: 46850, status: 'completed', reference: 'BAL-OPEN', note: 'Available balance brought forward', createdAt: minutesAgo(60 * 24 * 10) },
  { id: 'led_6', memberId: DEMO_USER_ID, type: 'ride_payment', amount: -1500, status: 'completed', reference: 'BKG-LIVE', note: 'Seat with Ade Bamidele', createdAt: minutesAgo(90) },
];

export function createSeedState(): PlatformState {
  return {
    version: 1,
    session: null,
    members,
    vehicles,
    rides,
    communities: COMMUNITIES,
    search: {
      fromId: 'ajah',
      toId: 'vi',
      time: '7:00 AM',
      seats: 1,
      recurring: true,
      sort: 'match',
      verifiedOnly: false,
      recurringOnly: false,
      communityOnly: false,
    },
    bookings: [
      {
        id: 'BKG-LIVE',
        rideId: 'CT2841',
        riderId: DEMO_USER_ID,
        seats: 1,
        amount: 1500,
        protectionFee: 120,
        discount: 120,
        total: 1500,
        status: 'paid',
        pin: '4827',
        pickupNote: 'Novare Mall main entrance',
        createdAt: minutesAgo(120),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-FRI',
        rideId: 'CT9102',
        riderId: DEMO_USER_ID,
        seats: 1,
        amount: 1350,
        protectionFee: 120,
        discount: 120,
        total: 1350,
        status: 'paid',
        pin: '1934',
        createdAt: minutesAgo(60 * 18),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-DAMI',
        rideId: 'CT8824',
        riderId: 'usr_dami',
        seats: 1,
        amount: 1500,
        protectionFee: 120,
        discount: 120,
        total: 1500,
        status: 'paid',
        pin: '4827',
        pickupNote: 'Oniru Market',
        createdAt: minutesAgo(40),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-TOBI',
        rideId: 'CT8824',
        riderId: 'usr_tobi',
        seats: 1,
        amount: 1500,
        protectionFee: 120,
        discount: 120,
        total: 1500,
        status: 'requested',
        pin: '4827',
        pickupNote: 'Abraham Adesanya Estate Gate',
        createdAt: minutesAgo(12),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-AMAKA',
        rideId: 'CT8901',
        riderId: 'usr_amaka',
        seats: 1,
        amount: 1500,
        protectionFee: 120,
        discount: 120,
        total: 1500,
        status: 'requested',
        pin: '2201',
        pickupNote: 'Law School, VI',
        createdAt: minutesAgo(25),
        ratedByRider: false,
        ratedByDriver: false,
      },
    ],
    trips: [
      {
        id: 'TRIP-LIVE',
        rideId: 'CT2841',
        status: 'driver_en_route',
        pin: '4827',
        etaMinutes: 6,
        progress: 38,
        startedAt: minutesAgo(8),
      },
      {
        id: 'TRIP-FRI',
        rideId: 'CT9102',
        status: 'scheduled',
        pin: '1934',
        etaMinutes: 46,
        progress: 0,
      },
      {
        id: 'TRIP-EVE',
        rideId: 'CT8824',
        status: 'scheduled',
        pin: '4827',
        etaMinutes: 48,
        progress: 0,
      },
    ],
    messages: [
      { id: 'msg_1', tripId: 'TRIP-LIVE', fromId: 'usr_ade', text: "I'm two minutes from Novare Mall.", at: minutesAgo(4) },
      { id: 'msg_2', tripId: 'TRIP-LIVE', fromId: DEMO_USER_ID, text: "I'm at the main entrance.", at: minutesAgo(3) },
    ],
    notifications: [
      {
        id: 'nt_1',
        memberId: DEMO_USER_ID,
        title: 'Ade is on the way',
        body: 'Your driver is 6 minutes from Novare Mall.',
        kind: 'trip',
        read: false,
        at: minutesAgo(6),
      },
      {
        id: 'nt_2',
        memberId: DEMO_USER_ID,
        title: 'New seat request',
        body: 'Tobi Nwankwo requested 1 seat on your 5:30 PM ride.',
        kind: 'booking',
        read: false,
        at: minutesAgo(12),
      },
      {
        id: 'nt_3',
        memberId: DEMO_USER_ID,
        title: 'Payment held',
        body: '₦1,500 is held securely until your trip with Ade is completed.',
        kind: 'payment',
        read: true,
        at: minutesAgo(90),
      },
    ],
    ledger,
    emergencies: [],
    ratings: [],
  };
}

export { now };
