import type {
  AtRiskIntervention,
  Community,
  LedgerEntry,
  Member,
  PlatformState,
  RecurringSchedule,
  RideOffer,
  Vehicle,
} from './types';

export const DEMO_PHONE = '08031112841';
export const DEMO_OTP = '4827';
export const DEMO_USER_ID = 'usr_olabisi';
export const STORAGE_KEY = 'comuta.v2';

export const COMMUNITIES: Community[] = [
  { id: 'com_sterling', name: 'COMUTA at Marina & Sterling', type: 'Workplace', members: '540', routes: 16, color: '#d8f3e5', initials: 'MS' },
  { id: 'com_vi_tech', name: 'VI & Lekki Tech Corridor', type: 'Professional', members: '1,420', routes: 32, color: '#ece4ff', initials: 'VT' },
  { id: 'com_ikorodu', name: 'Ikorodu Island Commuters', type: 'Corridor Circle', members: '890', routes: 24, color: '#fff0cd', initials: 'IC' },
  { id: 'com_unilag', name: 'Mainland Alumni Circle', type: 'University', members: '760', routes: 18, color: '#e1efff', initials: 'AC' },
];

const members: Member[] = [
  {
    id: DEMO_USER_ID,
    firstName: 'Olabisi',
    lastName: 'Ojo',
    phone: DEMO_PHONE,
    email: 'olabisi@comuta.ng',
    initials: 'OO',
    avatarColor: '#1c604c',
    rating: 4.95,
    trips: 34,
    verified: true,
    communityIds: ['com_ikorodu', 'com_sterling'],
    emergencyContacts: [{ name: 'Funmi Ojo', phone: '0805 441 2290', relation: 'Sister' }],
    licenceNumber: 'LAG-20491832',
    bankName: 'Guaranty Trust Bank',
    bankLast4: '0294',
    cardLast4: '2048',
    driverReliability: {
      overallScore: 98,
      completionRate: 98,
      onTimeRate: 97,
      lateCancellations: 1,
      noShows: 0,
      tips: [
        'Confirm tomorrow’s trip by 11:00 PM to keep your 98% commitment badge.',
        'Arrive at Ikorodu Hub Main Gate 5 minutes before scheduled 7:00 AM departure.',
      ],
    },
  },
  {
    id: 'usr_adebayo',
    firstName: 'Adebayo',
    lastName: 'K.',
    phone: '0802 441 1182',
    initials: 'AK',
    avatarColor: '#0c392c',
    photo: '/images/people/ade.jpg',
    rating: 4.96,
    trips: 188,
    verified: true,
    communityIds: ['com_ikorodu', 'com_sterling'],
    emergencyContacts: [{ name: 'Yemi K.', phone: '0803 123 4567', relation: 'Spouse' }],
    licenceNumber: 'LAG-11820344',
    bankName: 'Access Bank',
    bankLast4: '4412',
    driverReliability: {
      overallScore: 98,
      completionRate: 98,
      onTimeRate: 97,
      lateCancellations: 1,
      noShows: 0,
      tips: [
        'Maintain on-time hub departures to stay in the 98%+ trusted tier.',
        'Respond promptly to T-8 confirmation reminders before 11:00 PM.',
      ],
    },
  },
  {
    id: 'usr_ifeoma',
    firstName: 'Ifeoma',
    lastName: 'N.',
    phone: '0813 220 9041',
    initials: 'IN',
    avatarColor: '#7656b8',
    photo: '/images/people/ifeoma.jpg',
    rating: 4.92,
    trips: 112,
    verified: true,
    communityIds: ['com_vi_tech'],
    emergencyContacts: [],
    licenceNumber: 'LAG-90331120',
    driverReliability: {
      overallScore: 99,
      completionRate: 99,
      onTimeRate: 98,
      lateCancellations: 0,
      noShows: 0,
      tips: ['Consistent 5-star driver.'],
    },
  },
  {
    id: 'usr_musa',
    firstName: 'Musa',
    lastName: 'L.',
    phone: '0706 239 1104',
    initials: 'ML',
    avatarColor: '#257769',
    photo: '/images/people/musa.jpg',
    rating: 4.88,
    trips: 245,
    verified: true,
    communityIds: ['com_ikorodu'],
    emergencyContacts: [],
    driverReliability: {
      overallScore: 97,
      completionRate: 97,
      onTimeRate: 96,
      lateCancellations: 1,
      noShows: 0,
      tips: ['High corridor frequency.'],
    },
  },
  {
    id: 'usr_chidi',
    firstName: 'Chidi',
    lastName: 'O.',
    phone: '0803 991 2044',
    initials: 'CO',
    avatarColor: '#3c7b6e',
    photo: '/images/people/chidi.jpg',
    rating: 4.85,
    trips: 74,
    verified: true,
    communityIds: ['com_unilag'],
    emergencyContacts: [],
    driverReliability: {
      overallScore: 96,
      completionRate: 96,
      onTimeRate: 95,
      lateCancellations: 1,
      noShows: 0,
      tips: ['Great passenger ratings.'],
    },
  },
  {
    id: 'usr_damilola',
    firstName: 'Damilola',
    lastName: 'J.',
    phone: '0809 332 4410',
    initials: 'DJ',
    avatarColor: '#bd8352',
    photo: '/images/people/seyi.jpg',
    rating: 4.8,
    trips: 58,
    verified: true,
    communityIds: ['com_vi_tech'],
    emergencyContacts: [],
  },
  {
    id: 'usr_tobi',
    firstName: 'Tobi',
    lastName: 'N.',
    phone: '0812 667 3901',
    initials: 'TN',
    avatarColor: '#7059a3',
    photo: '/images/people/chidi.jpg',
    rating: 4.9,
    trips: 22,
    verified: true,
    communityIds: ['com_sterling'],
    emergencyContacts: [],
  },
  {
    id: 'usr_amaka',
    firstName: 'Amaka',
    lastName: 'E.',
    phone: '0805 118 2293',
    initials: 'AE',
    avatarColor: '#cc7955',
    photo: '/images/people/amaka.jpg',
    rating: 4.95,
    trips: 46,
    verified: true,
    communityIds: ['com_ikorodu'],
    emergencyContacts: [],
  },
];

const vehicles: Vehicle[] = [
  { id: 'veh_adebayo', driverId: 'usr_adebayo', make: 'Toyota', model: 'Corolla', color: 'Silver', plate: 'ABC 123 XY', seats: 4, year: 2019 },
  { id: 'veh_ifeoma', driverId: 'usr_ifeoma', make: 'Honda', model: 'Accord', color: 'Black', plate: 'KJA 208 FT', seats: 4, year: 2020 },
  { id: 'veh_musa', driverId: 'usr_musa', make: 'Kia', model: 'Rio', color: 'Blue', plate: 'GGE 774 BX', seats: 4, year: 2021 },
  { id: 'veh_chidi', driverId: 'usr_chidi', make: 'Toyota', model: 'Camry', color: 'White', plate: 'LND 902 EK', seats: 4, year: 2018 },
  { id: 'veh_olabisi', driverId: DEMO_USER_ID, make: 'Toyota', model: 'Corolla', color: 'Silver', plate: 'APP 882 LK', seats: 4, year: 2019 },
];

const weekdays = [1, 2, 3, 4, 5];

const rides: RideOffer[] = [
  {
    id: 'CM-IKR-01',
    driverId: 'usr_adebayo',
    vehicleId: 'veh_adebayo',
    fromId: 'ikorodu-hub',
    toId: 'vi-hub',
    pickupId: 'ikorodu-hub',
    dropoffId: 'vi-hub',
    time: '7:00 AM',
    durationMin: 65,
    distanceKm: 34.2,
    price: 1500,
    seats: 4,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_ikorodu',
    status: 'published',
    when: 'tomorrow',
    confirmedByDriver: true,
    t8Deadline: '11:00 PM',
  },
  {
    id: 'CM-IKR-02',
    driverId: 'usr_ifeoma',
    vehicleId: 'veh_ifeoma',
    fromId: 'ikorodu-hub',
    toId: 'vi-hub',
    pickupId: 'ikorodu-hub',
    dropoffId: 'vi-hub',
    time: '6:45 AM',
    durationMin: 65,
    distanceKm: 34.2,
    price: 1400,
    seats: 4,
    seatsLeft: 1,
    recurring: true,
    days: weekdays,
    communityId: 'com_ikorodu',
    status: 'published',
    when: 'tomorrow',
    confirmedByDriver: true,
    t8Deadline: '11:00 PM',
  },
  {
    id: 'CM-IKR-03',
    driverId: 'usr_musa',
    vehicleId: 'veh_musa',
    fromId: 'ikorodu-hub',
    toId: 'vi-hub',
    pickupId: 'ikorodu-hub',
    dropoffId: 'vi-hub',
    time: '7:15 AM',
    durationMin: 65,
    distanceKm: 34.2,
    price: 1350,
    seats: 4,
    seatsLeft: 3,
    recurring: false,
    days: weekdays,
    communityId: 'com_ikorodu',
    status: 'published',
    when: 'tomorrow',
    confirmedByDriver: false,
    t8Deadline: '11:00 PM',
  },
  {
    id: 'CM-IKR-04',
    driverId: 'usr_chidi',
    vehicleId: 'veh_chidi',
    fromId: 'ikorodu-hub',
    toId: 'vi-hub',
    pickupId: 'ikorodu-hub',
    dropoffId: 'vi-hub',
    time: '7:30 AM',
    durationMin: 65,
    distanceKm: 34.2,
    price: 1500,
    seats: 4,
    seatsLeft: 2,
    recurring: true,
    days: weekdays,
    communityId: 'com_ikorodu',
    status: 'published',
    when: 'tomorrow',
    confirmedByDriver: true,
    t8Deadline: '11:00 PM',
  },
  {
    id: 'CM-DRV-01',
    driverId: DEMO_USER_ID,
    vehicleId: 'veh_olabisi',
    fromId: 'ikorodu-hub',
    toId: 'vi-hub',
    pickupId: 'ikorodu-hub',
    dropoffId: 'vi-hub',
    time: '7:00 AM',
    durationMin: 65,
    distanceKm: 34.2,
    price: 1500,
    seats: 4,
    seatsLeft: 1,
    recurring: true,
    days: weekdays,
    communityId: 'com_ikorodu',
    status: 'published',
    when: 'tomorrow',
    confirmedByDriver: false,
    t8Deadline: '11:00 PM',
  },
];

const minutesAgo = (n: number) => new Date(Date.now() - n * 60000).toISOString();

const ledger: LedgerEntry[] = [
  { id: 'led_1', memberId: DEMO_USER_ID, type: 'settlement', amount: 4500, status: 'completed', reference: 'CM-SETT-01', note: 'Commute Cost Recovery · 3 seats filled', createdAt: minutesAgo(60 * 24 * 2) },
  { id: 'led_2', memberId: DEMO_USER_ID, type: 'ride_payment', amount: -1500, status: 'completed', reference: 'CM-BKG-HERO', note: 'COMUTA seat · Adebayo K. (Toyota Corolla)', createdAt: minutesAgo(180) },
  { id: 'led_3', memberId: DEMO_USER_ID, type: 'settlement', amount: 3000, status: 'completed', reference: 'CM-SETT-02', note: 'Commute Cost Recovery · 2 seats filled', createdAt: minutesAgo(60 * 24 * 5) },
];

const recurringCommutes: RecurringSchedule[] = [
  {
    id: 'REC-01',
    fromHub: 'Ikorodu Hub',
    toHub: 'Victoria Island Hub',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    time: '7:00 AM',
    price: 1500,
    status: 'active',
    driverName: 'Adebayo K.',
    driverCar: 'Toyota Corolla · ABC 123 XY',
  },
];

const atRiskInterventions: AtRiskIntervention[] = [
  {
    id: 'ATRISK-01',
    driverId: 'usr_musa',
    driverName: 'Musa L.',
    route: 'Ikorodu Hub → Victoria Island Hub',
    time: '7:15 AM',
    issue: 'T-8 confirmation pending (22 min to cutoff)',
    status: 'open',
    passengers: 3,
    alternativeDriver: 'Ifeoma N. (6:45 AM) / Chidi O. (7:30 AM)',
  },
  {
    id: 'ATRISK-02',
    driverId: 'usr_damilola',
    driverName: 'Damilola J.',
    route: 'Berger Hub → Victoria Island Hub',
    time: '6:30 AM',
    issue: 'Vehicle cooling system alert reported',
    status: 'open',
    passengers: 4,
    alternativeDriver: 'Tolu A. (Honda Civic)',
  },
  {
    id: 'ATRISK-03',
    driverId: 'usr_chidi',
    driverName: 'Chidi O.',
    route: 'Yaba Hub → Lekki Hub',
    time: '7:45 AM',
    issue: 'Corridor roadworks delay flagged on Third Mainland',
    status: 'open',
    passengers: 2,
    alternativeDriver: 'Seyi O. (Toyota Corolla)',
  },
];

export function createSeedState(): PlatformState {
  return {
    version: 1,
    session: {
      memberId: DEMO_USER_ID,
      role: 'rider',
      onboarded: true,
      driverOnboarded: true,
    },
    members,
    vehicles,
    rides,
    communities: COMMUNITIES,
    search: {
      fromId: 'ikorodu-hub',
      toId: 'vi-hub',
      time: '7:00 AM',
      seats: 1,
      recurring: true,
      sort: 'match',
      verifiedOnly: false,
      recurringOnly: false,
      communityOnly: false,
    },
    recurringCommutes,
    atRiskInterventions,
    bookings: [
      {
        id: 'BKG-HERO-01',
        rideId: 'CM-IKR-01',
        riderId: DEMO_USER_ID,
        seats: 1,
        amount: 1500,
        protectionFee: 0,
        discount: 0,
        total: 1500,
        status: 'confirmed',
        pin: '4827',
        pickupNote: 'Main Gate · Well-lit pickup point',
        pickupHub: 'Ikorodu Hub',
        dropoffHub: 'Victoria Island Hub',
        createdAt: minutesAgo(180),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-DRV-PASS-1',
        rideId: 'CM-DRV-01',
        riderId: 'usr_tobi',
        seats: 1,
        amount: 1500,
        protectionFee: 0,
        discount: 0,
        total: 1500,
        status: 'confirmed',
        pin: '4827',
        pickupNote: 'Ikorodu Hub Main Gate',
        createdAt: minutesAgo(90),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-DRV-PASS-2',
        rideId: 'CM-DRV-01',
        riderId: 'usr_amaka',
        seats: 1,
        amount: 1500,
        protectionFee: 0,
        discount: 0,
        total: 1500,
        status: 'confirmed',
        pin: '7721',
        pickupNote: 'Ikorodu Hub Main Gate',
        createdAt: minutesAgo(60),
        ratedByRider: false,
        ratedByDriver: false,
      },
      {
        id: 'BKG-DRV-PASS-3',
        rideId: 'CM-DRV-01',
        riderId: 'usr_damilola',
        seats: 1,
        amount: 1500,
        protectionFee: 0,
        discount: 0,
        total: 1500,
        status: 'confirmed',
        pin: '3390',
        pickupNote: 'Ikorodu Hub Main Gate',
        createdAt: minutesAgo(30),
        ratedByRider: false,
        ratedByDriver: false,
      },
    ],
    trips: [
      {
        id: 'TRIP-HERO-01',
        rideId: 'CM-IKR-01',
        status: 'driver_confirmed',
        pin: '4827',
        etaMinutes: 32,
        progress: 45,
        startedAt: minutesAgo(20),
        driverConfirmed: true,
      },
      {
        id: 'TRIP-DRV-01',
        rideId: 'CM-DRV-01',
        status: 'scheduled',
        pin: '4827',
        etaMinutes: 65,
        progress: 0,
        driverConfirmed: false,
      },
    ],
    messages: [
      { id: 'msg_1', tripId: 'TRIP-HERO-01', fromId: 'usr_adebayo', text: 'Good evening Olabisi. I have confirmed our 7:00 AM commute tomorrow from Ikorodu Hub Main Gate.', at: minutesAgo(120) },
      { id: 'msg_2', tripId: 'TRIP-HERO-01', fromId: DEMO_USER_ID, text: 'Noted Adebayo, see you at the gate by 6:55 AM!', at: minutesAgo(110) },
    ],
    notifications: [
      {
        id: 'nt_1',
        memberId: DEMO_USER_ID,
        title: 'Commute Confirmed',
        body: 'Adebayo K. confirmed your 7:00 AM Ikorodu → Victoria Island trip.',
        kind: 'trip',
        read: false,
        at: minutesAgo(120),
      },
      {
        id: 'nt_2',
        memberId: DEMO_USER_ID,
        title: 'T-8 Reminder for Tomorrow',
        body: 'Your driver Adebayo K. verified commitment. Your seat is guaranteed.',
        kind: 'trip',
        read: false,
        at: minutesAgo(240),
      },
      {
        id: 'nt_3',
        memberId: DEMO_USER_ID,
        title: 'Cost Recovery Update',
        body: '₦4,500 credited to your commute balance this month.',
        kind: 'payment',
        read: true,
        at: minutesAgo(60 * 24 * 2),
      },
    ],
    ledger,
    emergencies: [],
    ratings: [],
  };
}
